config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :channels
  resources :users
  resources :platforms
  resources :schedules
  resources :fighters
  resources :main_event_fighters
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :user
  belongs_to :platform
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :platform
  has_many :schedules
  has_many :fighters, through: :schedules
  has_one :main_event_fighter
end

app/models/fighter.rb
class Fighter < ApplicationRecord 
    has_many :schedules
    has_many :events, through: :schedules
end

app/models/main_event_fighter.rb
class MainEventFighter < ApplicationRecord 

end

app/models/platform.rb
class Platform < ApplicationRecord
    has_many :events
    has_many :channels
    has_many :schedules, through: :events
    has_many :users, through: :channels

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :event
  belongs_to :fighter

  validates :event_id, uniqueness: {scope: :fighter_id, message: "Fighter already booked"}
end

app/models/user.rb
class User < ApplicationRecord
    has_many :channels 
    has_many :platforms, through: :channels
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController


    def index
        @events = Event.all
    end
    
    def show 
        @event = Event.find(params[:id])   
    end
    
    def new 
        @event = Event.new
    end
    
    private

    def event_params
        params.require(:event).permit
    end  

end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController

    def index
        @fighters = Fighter.all
    end
    
    def show 
        @fighter = Fighter.find(params[:id])
    end
    
    def new 
        @fighter = Fighter.new
    end
    
    private

    def fighter_params
        params.require(:fighter).permit
    end    

end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController


    def index
        @platforms = Platform.all
    end
    
    def show 
        @platform = Platform.find(params[:id])
    end
    
    def new 
        @platform = Platform.new
    end
    
    private

    def platform_params
        params.require(:platform).permit
    end  

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
    def index
        @schedule = Schedule.all
        
    end

    def new 
        @schedules = Schedule.new
        @platforms = Platform.all
        @events = Event.all
        @fighters = Fighter.all 
    end
    
    def create
        @schedule = Schedule.create(schedule_params)
        redirect_to event_path(@schedule.event.id)
    end

    def edit
        @schedule = Schedule.find(params[:id])
        @events = Event.all 
        @fighters = Fighter.all
    end

    def update
        @schedule = Schedule.find(params[:id])
        @schedule.update(schedule_params)
        redirect_to event_path(@schedule.event.id)
    end

    def destroy
        @schedule = Schedule.find(params[:id])
        @schedule.destroy
        redirect_to event_path(@schedule.event.id)
    end



    private

    def schedule_params
        params.require(:schedule).permit(:platform_id, :event_id, :fighter_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    
    def show 
        @user = User.find(params[:id])
    end

    def new 
        @user = User.new
    end
    
    def create
        @user = User.create(user_params)
        redirect_to user_path(@user.user_id)
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        redirect_to user_path(@user)
    end

    def destroy
        @user = user.find(params[:id])
        @user.destroy
        redirect_to user_path
    end



    private

    def user_params
        param.require(:user).permit(:name, :age)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/fighters_helper.rb
module FightersHelper
end

app/helpers/platforms_helper.rb
module PlatformsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/Fighter/index.html.erb
<h1>Fighters</h1>

<ul>

    <% @fighters.each do |fighter| %>
        <li>
            <%= link_to fighter.name, fighter_path(fighter) %>
        </li>
    <% end %>
</ul>

app/views/events/index.html.erb
<h2>            Events          </h2>


<ul> 
    <% @events.each do |event| %>
        <li>
            <%= link_to event.name, event_path(event) %>
        </li>
    <% end %>
</ul>            

app/views/events/show.html.erb
<h2 class="event-header"> Event </h2>

<p> Name: <%= @event.name %> </p>
<p> Viewing: <%= @event.platform.name %> </p>
<p> location: <%= @event.location %> </p>



<img src="<%= @event.image_url %>" >




<h2> List of Fighters </h2>

<ol>
    <% @event.fighters.each do |fighter_inst| %>
        <li>
            <%=link_to fighter_inst.name, fighter_path(fighter_inst) %> 
        </li>
    <%end%>
</ol>

<ol>
        <% @event.schedules.each do |schedule| %>
            <%= schedule.fighter.name %>
            <%= button_to "x", "/schedules/#{schedule.id}", method: "delete" %>
        <% end %>    
</ol>

app/views/fighters/index.html.erb
           <h1>Fighters</h1>

<ul>
    <% @fighters.each do |fighter| %>
        <li>
            <%= link_to fighter.name, fighter_path(fighter) %>
        </li>
    <% end %>
</ul>

app/views/fighters/show.html.erb
<h2 class="fighter-header"> Fighter </h2>

<h2> Name: <%= @fighter.name %> </h2> 
<p> Style: <%= @fighter.style %> </p>
<p> record: <%= @fighter.fighting_record %> </p>

<img src="<%= @fighter.image_url %>" >

app/views/platforms/index.html.erb
<h1>Platforms</h1>

<ul>
    <% @platforms.each do |platform| %>
        <li>
            <%= link_to platform.name, platform_path(platform) %>
        </li>
    <% end %>
</ul>

app/views/platforms/show.html.erb
<h2 class="platform-header"> Platform </h2>

<h2> Name: <%= @platform.name %> </h2> 

app/views/schedules/edit.html.erb
<h1> Edit Schedule</h1>

<%= form_for @schedule do |f| %>


        <%= f.label :event_id %>
        <%= f.collection_select :event_id, @events, :id, :name %>
        <%= f.label :fighter_id %>
        <%= f.collection_select :fighter_id, @fighters, :id, :name %>
        <%= f.submit %>
    
<%end%>
    
    

app/views/schedules/new.html.erb
<h1> Book a Fighter </h1>

<% if flash[:errors] %>
    <ul>
        <% flash[:errors].each do |message| %>
            <li>
                <%= message %>
            </li>
        <%end%>
    </ul>
<%end%>



<%= form_for @schedules do |f| %>

    <%= f.label :event_id %>
    <%= f.collection_select :event_id, @events, :id, :name %>
    <%= f.label :fighter_id %>
    <%= f.collection_select :fighter_id, @fighters, :id, :name %>
    <%= f.submit %>

<%end%>

app/views/users/edit.html.erb
<h1>Edit Account <%=User.name%></h1>

    <%= form_for @user do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :age %>
        <%= f.text_field :age %>
        
    <%end%>

        

app/views/users/index.html.erb
<h2>            Users          </h2>


<ul> 
    <% @users.each do |user| %>
        <li>
            <%= link_to user.name, user_path(user) %>
        </li>
    <% end %>
</ul>      

app/views/users/new.html.erb
<h1> Create a Account </h1>

<%= form_for @user do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :age %>
    <%= f.text_field :age %>
    
<%end%>

app/views/users/show.html.erb
<h1> User show </h1>